import jwt from 'jsonwebtoken';
import User from '../models/User.js';
import Organization from '../models/Organization.js';

// Middleware to verify JWT token
export const authenticateToken = async (req, res, next) => {
  try {
    const authHeader = req.headers['authorization'];
    const token = authHeader && authHeader.split(' ')[1]; // Bearer TOKEN

    if (!token) {
      return res.status(401).json({ message: 'Access token required' });
    }

    // Support for mock OTP tokens generated by authController
    if (token.startsWith('token_')) {
      const parts = token.split('_');
      if (parts.length >= 2) {
        req.user = { role: 'patient', mobile: parts[1], _id: `patient_${parts[1]}` };
        return next();
      }
    }

    const jwtSecret = process.env.JWT_SECRET || 'your-secret-key';

    let decoded;
    try {
      decoded = jwt.verify(token, jwtSecret);
    } catch (jwtError) {
      console.log(`[AUTH] Token verification failed for ${req.method} ${req.url}:`, jwtError.message);
      if (jwtError.name === 'TokenExpiredError') {
        return res.status(401).json({ message: 'Token expired. Please login again.' });
      }
      return res.status(401).json({ message: 'Invalid token. Please login again.' });
    }

    const user = await User.findById(decoded.id).populate('organizationId');
    if (!user) {
      console.log(`[AUTH] User not found for decoded ID: ${decoded.id} (Role: ${decoded.role}) at ${req.method} ${req.url}`);
      return res.status(401).json({ message: 'Session invalid - user record not found' });
    }

    // Check if password was changed after this token was issued
    if (user.passwordLastChanged) {
      const passwordChangedTime = Math.floor(user.passwordLastChanged.getTime() / 1000);
      // Add a 60-second grace period to account for clock drift between servers
      if (decoded.iat < (passwordChangedTime - 60)) {
        console.log(`[AUTH] Token invalidated for user ${user.name}: Password changed after token issuance.`);
        return res.status(401).json({ message: 'Session expired due to password change. Please login again.' });
      }
    }

    // For non-superadmin users, verify organization is active (only if they have an organizationId)
    if (user.role !== 'superadmin' && user.organizationId) {
      try {
        const org = await Organization.findById(user.organizationId);
        if (!org) {
          console.log(`[AUTH] Organization ${user.organizationId} not found for user ${user.name}`);
          return res.status(403).json({ message: 'Your organization account is suspended or inactive' });
        }
        if (org.status === 'suspended' || org.status === 'inactive') {
          console.log(`[AUTH] Organization ${org.name} is ${org.status} for user ${user.name}`);
          return res.status(403).json({ 
            message: 'account_deactivated',
            details: 'Your account has been suspended or deactivated by the administrator. Please contact support for more details.'
          });
        }
      } catch (orgError) {
        // If organization lookup fails, allow the request to proceed
        console.warn('[AUTH] Organization lookup failed:', orgError.message);
      }
    }

    req.user = user;
    
    // Set tenantId from user's organization - ALWAYS take precedence over headers for authenticated requests
    if (user.organizationId) {
      req.tenantId = user.organizationId._id || user.organizationId;
    }
    
    next();
  } catch (error) {
    console.error('[AUTH] Unhandled error in auth middleware:', error);
    res.status(401).json({ message: 'Authentication failed' });
  }
};

// Middleware to check if user has admin role (doctor/admin)
export const requireAdmin = (req, res, next) => {
  if (!req.user) {
    return res.status(401).json({ message: 'Authentication required' });
  }

  if (req.user.role !== 'admin' && req.user.role !== 'superadmin' && req.user.role !== 'orgadmin') {
    return res.status(403).json({ message: 'Admin access required' });
  }

  next();
};

// Middleware to check if user has admin or doctor role
export const requireAdminOrDoctor = (req, res, next) => {
  if (!req.user) {
    return res.status(401).json({ message: 'Authentication required' });
  }

  if (req.user.role !== 'admin' && req.user.role !== 'superadmin' && req.user.role !== 'orgadmin' && req.user.role !== 'doctor') {
    return res.status(403).json({ message: 'Admin or Doctor access required' });
  }

  next();
};

// Middleware to check if user is organization admin
export const requireOrgAdmin = (req, res, next) => {
  if (!req.user) {
    return res.status(401).json({ message: 'Authentication required' });
  }

  if (req.user.role !== 'orgadmin' && req.user.role !== 'superadmin') {
    return res.status(403).json({ message: 'Organization admin access required' });
  }

  next();
};

// Middleware to check if user has admin or receptionist role
export const requireAdminOrReceptionist = (req, res, next) => {
  if (!req.user) {
    return res.status(401).json({ message: 'Authentication required' });
  }

  if (req.user.role !== 'admin' && req.user.role !== 'superadmin' && req.user.role !== 'orgadmin' && req.user.role !== 'receptionist') {
    return res.status(403).json({ message: 'Admin or Receptionist access required' });
  }

  next();
};

// Middleware to check if user has superadmin role
export const requireSuperAdmin = (req, res, next) => {
  if (!req.user) {
    return res.status(401).json({ message: 'Authentication required' });
  }

  if (req.user.role !== 'superadmin') {
    return res.status(403).json({ message: 'Super admin access required' });
  }

  next();
};

// Middleware to check if user has pharmacy role
export const requirePharmacy = (req, res, next) => {
  if (!req.user) {
    return res.status(401).json({ message: 'Authentication required' });
  }

  if (req.user.role !== 'pharmacy') {
    return res.status(403).json({ message: 'Pharmacy access required' });
  }

  next();
};