import React from 'react';
import { motion } from 'framer-motion';
import { FileText, Shield, Sparkles, Scale, Lock, AlertTriangle } from 'lucide-react';
import PublicHeader from '../components/Shared/PublicHeader';
import PublicFooter from '../components/Shared/PublicFooter';

const TermsAndConditions = () => {
  const sections = [
    {
      icon: <Sparkles className="text-blue-500" />,
      title: "1. Maya AI Disclaimer",
      content: (
        <div className="space-y-4 text-slate-600">
          <div className="p-4 bg-amber-50 border border-amber-100 rounded-2xl flex items-start gap-3">
             <AlertTriangle className="text-amber-500 shrink-0 mt-0.5" size={18} />
             <p className="text-xs font-bold text-amber-800 leading-relaxed">
               IMPORTANT: Maya AI is an experimental artificial intelligence feature. 
               Information provided is for general knowledge and should NOT be considered professional medical advice.
             </p>
          </div>
          <ul className="list-disc pl-5 space-y-2">
            <li><strong>No Medical Advice:</strong> Maya AI does not provide diagnosis, treatment, or clinical recommendations.</li>
            <li><strong>Verification Required:</strong> All information generated by Maya AI must be verified with a qualified healthcare professional.</li>
            <li><strong>Liability:</strong> Slotify Professional is not responsible for any actions taken based on AI-generated responses. AI can make mistakes.</li>
          </ul>
        </div>
      )
    },
    {
      icon: <Shield className="text-emerald-500" />,
      title: "2. Scope of Service",
      content: (
        <div className="space-y-3 text-slate-600">
          <p>Slotify Professional is an appointment management and clinic operations platform.</p>
          <ul className="list-disc pl-5 space-y-2">
            <li>We do not provide medical services directly.</li>
            <li>We facilitate scheduling and record-keeping between patients and healthcare providers.</li>
            <li>Clinical outcomes are the sole responsibility of the attending healthcare provider.</li>
          </ul>
        </div>
      )
    },
    {
      icon: <FileText className="text-purple-500" />,
      title: "3. User Responsibilities",
      content: (
        <div className="space-y-3 text-slate-600">
          <p>By using the platform, you agree to:</p>
          <ul className="list-disc pl-5 space-y-2">
            <li>Provide accurate and complete personal and medical information.</li>
            <li>Maintain the security of your account and mobile login.</li>
            <li>Use the automated booking tools only for genuine therapeutic purposes.</li>
          </ul>
        </div>
      )
    },
    {
      icon: <Scale className="text-orange-500" />,
      title: "4. Limitation of Liability",
      content: (
        <p className="text-slate-600 leading-relaxed">
          To the maximum extent permitted by law, Slotify Professional shall not be 
          liable for any indirect, incidental, or consequential damages resulting from the use of 
          the service. Our total liability is limited to the amount paid for the service in the rolling 12 months.
        </p>
      )
    },
    {
      icon: <Lock className="text-teal-500" />,
      title: "5. Intellectual Property",
      content: (
        <p className="text-slate-600 leading-relaxed">
          The software, including the Maya AI engine, UI designs, and brand assets, are the exclusive property 
          of Slotify. Unauthorized reproduction or reverse engineering is strictly prohibited.
        </p>
      )
    }
  ];

  return (
    <div className="min-h-screen bg-slate-50">
      <PublicHeader />
      
      {/* Hero Section */}
      <section className="pt-32 pb-16 px-4 bg-white border-b border-slate-100">
        <div className="max-w-4xl mx-auto text-center">
          <motion.div
            initial={{ opacity: 0, scale: 0.9 }}
            animate={{ opacity: 1, scale: 1 }}
            className="inline-flex items-center gap-2 px-4 py-2 bg-slate-100 text-slate-600 rounded-full mb-6"
          >
            <Scale size={16} />
            <span className="text-sm font-bold uppercase tracking-wider">Legal Framework</span>
          </motion.div>
          <h1 className="text-4xl md:text-5xl font-black text-slate-900 mb-6">Terms and Conditions</h1>
          <p className="text-lg text-slate-500 font-medium max-w-2xl mx-auto">
            These terms govern your use of the Slotify Professional platform and our AI-powered features.
          </p>
        </div>
      </section>

      {/* Content Section */}
      <section className="py-16 px-4">
        <div className="max-w-4xl mx-auto space-y-8">
          {sections.map((section, idx) => (
            <motion.div
              key={idx}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              className="bg-white p-8 rounded-3xl border border-slate-200 shadow-sm"
            >
              <div className="flex items-start gap-4">
                <div className="mt-1 p-3 bg-slate-50 rounded-2xl">
                  {section.icon}
                </div>
                <div className="flex-1">
                  <h2 className="text-xl font-black text-slate-900 mb-4">{section.title}</h2>
                  {section.content}
                </div>
              </div>
            </motion.div>
          ))}

          <div className="bg-slate-900 text-white p-8 rounded-3xl text-center shadow-xl">
            <h2 className="text-2xl font-black mb-4 uppercase tracking-wider">Agreement Notice</h2>
            <p className="text-slate-400 mb-0 font-medium leading-relaxed">
              By clicking "Accept" or continuing to use the platform, you acknowledge that you have 
              read, understood, and agreed to be bound by these Terms and Conditions and our Privacy Policy.
            </p>
          </div>
          
          <div className="text-center py-8">
            <p className="text-slate-400 text-sm font-medium">
              Last Updated: April 5, 2026 • © {new Date().getFullYear()} Slotify Professional
            </p>
          </div>
        </div>
      </section>

      <PublicFooter />
    </div>
  );
};

export default TermsAndConditions;
